baseURL = "https://dcustudentbot.netlify.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "DCU Student Bot"
theme = "hallo"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "the DCU Student Bot"

[params]

    [[params.links]]
        icon = "discord"
        title = "Discord"
        url = "https://discord.gg/kVDRFdFerR"

    [[params.links]]
        icon = "facebook"
        title = "Facebook"
        url = "https://facebook.com/DCURuby"

    [params.colors]
        background = "#00008B"
        foreground = "#edf7ff"
        hover = "#ffba82"
      
